### ISSUE TITLE
Theme modification

### ISSUE THREAD

**Issue by MosabWadea** [CybroOdoo/OpenHRMS#18]
Hi
I have installed the hrms tools from this repo. and I have few comments about the theme. first of all is it a must to have this theme? because I do prefer the backend theme from openworx. 

In case the theme is a must, can I customize the favicon? and can you guys implement the side "log panel"? The main thing I liked about the openworx theme is that the log panel is placed on the side of the screen for wide screens and it moves to the bottom when the screen is squeezed. can you please provide this feature.

Thanks

**Comment by CybroOdoo** [comment]
Hi,
Right now the OpenHrms theme is required for the other modules to get installed as it is given as dependent for other modules.

If you want to run the Openhrms with the openworx theme, you can change the dependency given for the module and do it.
