### ISSUE TITLE
Active:Failed (result:exit-code)

### ISSUE THREAD

**Issue by ayan87** [CybroOdoo/OpenHRMS#23]
Hi,
I am just try to install OPENHRMS application in ubuntu 16.04 and i am getting error in running a service 
sudo systemctl status openhrms-server

I am just enclosed a screenshot for the reference.

![111111](https://user-images.githubusercontent.com/48618458/54495203-38e47c00-48fb-11e9-9261-d28bc888aceb.jpg)

**Comment by CybroOdoo** [comment]
Hi,
Please install the PyPDF2 python package.
