### ISSUE TITLE
Server Error While Installing OpenHrms Core

### ISSUE THREAD

**Issue by hilarak** [CybroOdoo/OpenHRMS#25]
I am trying to install openhrms core with its dependencies. But a warning raises and could not forward.
@CybroOdoo 
![image](https://user-images.githubusercontent.com/24998694/55394831-4b90bf00-5551-11e9-95fa-f1781a02fcfd.png)

branch 11

**Comment by IvanBayan** [comment]
Same issue (or similar):
![Screenshot from 2019-04-11 13-53-09](https://user-images.githubusercontent.com/1370837/55952133-7a99e580-5c61-11e9-894d-f5f0361ea06b.png)

**Comment by niulinlnc** [comment]
You need to download the web_responsive module in [oca](https://github.com/OCA/web/tree/12.0/web_responsive)

**Comment by IvanBayan** [comment]
It works, thank you.

**Comment by CybroOdoo** [comment]
Hi
The Issue is fixed.

**Comment by hilarak** [comment]
Can you please reference the commit?
