### ISSUE TITLE
Unable to install module "hrms_dashboard" because an external dependency is not met: No module named pandas

### ISSUE THREAD

**Issue by gandhishilp** [CybroOdoo/OpenHRMS#29]
Unable to install module "hrms_dashboard" because an external dependency is not met: No module named pandas

**Comment by gandhishilp** [comment]
1512 INFO test odoo.addons.base.models.ir_module: ALLOW access to module.button_immediate_install on ['hrms_dashboard'] to user gan333333@gmail.com #2 via
1512 INFO test odoo.addons.base.models.ir_module: User #2 triggered module installation
1512 INFO test odoo.addons.base.models.ir_module: ALLOW access to module.button_install on ['hrms_dashboard'] to user gan######@gmail.com #2 via 124.123.96
1512 INFO test werkzeug: 124.123.96.56 - - [16/May/2019 16:34:04] "POST /web/dataset/call_button HTTP/1.1" 200 - 129 0.074 0.920
1512 INFO test werkzeug: 124.123.96.56 - - [16/May/2019 16:34:48] "POST /longpolling/poll HTTP/1.1" 200 - 8 0.005 50.134
1512 INFO test odoo.addons.base.models.ir_cron: Starting job `Post process payment transactions`.
1512 INFO test odoo.addons.base.models.ir_cron: Starting job `Reminder scheduler`.

**Comment by CybroOdoo** [comment]
Hi,
Please install the python package 'pandas'.

**Comment by vinayakybhatt** [comment]
installing the py package pandas didn't solve the problem. 
Need a solution ASAP.

**Comment by duckprince** [comment]
> installing the py package pandas didn't solve the problem.
> Need a solution ASAP.

i installed "pandas" package and it worked.

**Comment by husam-esco** [comment]
i did installed it too and its not working till now

**Comment by husam-esco** [comment]
Hi, 
i did the below commands and it solved 
pls follow the same seq. 

sudo apt-get update -y
sudo apt-get install -y python-pandas
pip3 install pandas

regards

**Comment by fourthcore** [comment]
> Hi,
> i did the below commands and it solved
> pls follow the same seq.
> 
> sudo apt-get update -y
> sudo apt-get install -y python-pandas
> pip3 install pandas
> 
> regards

I Follow this steps but same issues! any advice???

**Comment by husam-esco** [comment]
restart the service please and check

**Comment by fourthcore** [comment]
> restart the service please and check

I restarted, but same issues. perhaps file permission?

**Comment by nugroz** [comment]
> Hi,
> i did the below commands and it solved
> pls follow the same seq.
> 
> sudo apt-get update -y
> sudo apt-get install -y python-pandas
> pip3 install pandas
> 
> regards

solve with me with
sudo apt-get install -y python3-pandas

**Comment by shangpeng-dragon** [comment]
To enter the virtual environment to install

1.
cd /opt/odoo14
python3 -m venv odoo-venv
source odoo-venv/bin/activate
2.pip3 install pandas

**Comment by thoufeer** [comment]
> > Hi,
> > i did the below commands and it solved
> > pls follow the same seq.
> > sudo apt-get update -y
> > sudo apt-get install -y python-pandas
> > pip3 install pandas
> > regards
> 
> solve with me with sudo apt-get install -y python3-pandas

This one helped me to solve. Thank you.

**Comment by kiroomin** [comment]
> To enter the virtual environment to install
> 
> 
> cd /opt/odoo14 python3 -m venv odoo-venv source odoo-venv/bin/activate 2.pip3 install pandas

it work for me thanks baby

**Comment by ssemotom** [comment]
On windows follow the the steps below:
cd Odoo14\python>
then run the following three commands one by one:
python -m venv odoo-venv
odoo-venv/Scripts/activate
pip install pandas

**Comment by tessSnap** [comment]
> 

In addition to this on Windows, you may need to upgrade pandas and then add the path of the scripts to your environment variables 

1. python -m pip install --upgrade pandas
2. add 'C:\Program Files\Odoo\python\Scripts to your environment variables
