### ISSUE TITLE
Error: QWeb2: Template 'reminder_menu' not found

### ISSUE THREAD

**Issue by SebGJ** [CybroOdoo/OpenHRMS#3]
Hi,

We have an Odoo Community V11 installed on a Ubuntu server.

After installing hr_reminder we have this error message : 

`Erreur:
Error: QWeb2: Template 'reminder_menu' not found

https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:3689
Retraçage :
exception@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:3689:7
_render@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:3734:92
render@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:3730:146
renderElement@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:3949:1068
__widgetRenderAndInsert/<@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:3949:912
then/</</<@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:802:678
fire@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:796:281
add@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:797:467
then/</<@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:802:631
each@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:625:758
then/<@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:802:553
Deferred@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:803:189
then@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:802:518
__widgetRenderAndInsert@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:3949:879
prependTo@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:3949:214
_loadItems/<@https://crm.ixcys.com/web/content/840-af95866/web.assets_backend.js:756:707
_.forEach@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:12:558
_loadItems@https://crm.ixcys.com/web/content/840-af95866/web.assets_backend.js:756:565
start@https://crm.ixcys.com/web/content/840-af95866/web.assets_backend.js:756:288
OdooClass.extend/</prototype[name]</<@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:3816:485
show_application@https://crm.ixcys.com/web/content/840-af95866/web.assets_backend.js:505:1231
show_application@https://crm.ixcys.com/web/content/840-af95866/web.assets_backend.js:2596:2374
OdooClass.extend/Class.include/</prototype[name]</<@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:3819:368
start/<@https://crm.ixcys.com/web/content/840-af95866/web.assets_backend.js:501:2487
then/</</<@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:802:678
fire@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:796:281
fireWith@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:803:31
fire@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:796:281
add@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:797:467
then/</</<@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:802:753
fire@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:796:281
fireWith@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:803:31
fire@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:796:281
fireWith@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:803:31
fire@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:796:281
fireWith@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:803:31
fire@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:796:281
fireWith@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:803:31
fire@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:796:281
fireWith@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:803:31
loadJS/script.onreadystatechange@https://crm.ixcys.com/web/content/318-be42584/web.assets_common.js:3848:25`

Thank you for your help.

**Comment by Ilya-Kuchaev** [comment]
Server restart helped me )
