### ISSUE TITLE
Status code different in zk_machine.py and zkconst.py

### ISSUE THREAD

**Issue by beke** [CybroOdoo/OpenHRMS#30]
On line 66 in zk_machine.py says:
 if command == 2005:
                conn = True

but there is no status code 2005 in zkconst.py. What does status code 2005 mean?

**Comment by CybroOdoo** [comment]
Hi,
    from the  Protocol Description of ZKTeco's Standalone Devices , it returns 2005 code  when the connection is not authorized .Here we are simply checking is there any connections available ,if available we are proceeding with that device.
