### ISSUE TITLE
Cannot install OpenHRMS core - TypeError: Model 'hr.leave' does not exist in registry.

### ISSUE THREAD

**Issue by xneo1** [CybroOdoo/OpenHRMS#31]
When I try to install OpenHRMS core it returns:
TypeError: Model 'hr.leave' does not exist in registry.

On Technical Data>Dependencies
I cannot install (with the same error)"
-Open HRMS Multi-Company
-Open HRMS Leave Request Aliasing

Any ideas?
I'm on bitnami docker version 11

**Comment by CybroOdoo** [comment]
Hi,
Are you using Odoo 11 ?

**Comment by xneo1** [comment]
Yes Odoo 11

**Comment by CybroOdoo** [comment]
Please download and install OpenHRMS core V11 from this link,
https://www.odoo.com/apps/modules/11.0/ohrms_core/
You are trying to install the wrong version.

**Comment by xneo1** [comment]
Yes that's the one I downloaded and the problem comes from this.

**Comment by AlfonsoVertu** [comment]
Hi can u help me whit and docker image or whit a docker file for install odoo 11/12 whit your core in a container + container db? pls

**Comment by AlfonsoVertu** [comment]
Hi can u help me whit and docker image or whit a docker file for install odoo 11/12 whit your core in a container + container db? pls
