### ISSUE TITLE
Payroll Computation --- Enhancement / New Feature V11

### ISSUE THREAD

**Issue by rjay1018** [CybroOdoo/OpenHRMS#33]
Do we have this flexibility of computing the payroll base on the rules related to overtime and rest day policies? 

![overtime computation](https://user-images.githubusercontent.com/5526244/58303273-fa4ece80-7e21-11e9-96bd-470187c99f87.jpg)

Additional Information: Cola - Cost of Leaving Allowance

**Comment by CybroOdoo** [comment]
Hi,
Currently we do not have such options.
We can customize these options according to your requirement.
Please contact us to check the customization possibilities.

E-mail : info@cybrosys.com
