### ISSUE TITLE
hr.contract.type

### ISSUE THREAD

**Issue by msdeek** [CybroOdoo/OpenHRMS#42]
odoo.tools.convert.ParseError: "Invalid field 'view_type' on model 'ir.actions.act_window'" while parsing /odoo/custom/CybroOdoo/CybroAddons/hr_contract_types/views/contract_view.xml:3, near hr.contract.view.form.inherit hr.contract <xpath expr="//field[@name='job_id']" position="after"> hr.contract.type.form hr.contract.type hr.contract.type.tree hr.contract.type hr.contract.type.search hr.contract.type Contract Types hr.contract.type form tree,

**Comment by CybroOdoo** [comment]
Hi
The issue is fixed.
