### ISSUE TITLE
Unable to Install Open HRMS - HR Dashboard (hrms_dashboard) On Odoo 13 CE, Windows Environment

### ISSUE THREAD

**Issue by wshamasneh** [CybroOdoo/OpenHRMS#44]
I have tried to install Open HRMS - HR Dashboard (hrms_dashboard) on Odoo 13 CE, Windows Environment but without luck to complete it. An error shows up and here is the message:

Unable to install module "hrms_dashboard" because an external dependency is not met: Python library not installed: pandas

I have downloaded the pandas python library using the following command: pip install pandas, copy paste the installed folders into Odoo server (C:\Program Files (x86)\Odoo 13.0\server), restart both the application and the server but without any luck and the error still persists.

**Comment by CybroOdoo** [comment]
Hi
It is not the issue of the module. You have to configure the library 'pandas' properly.
