### ISSUE TITLE
[13.0] hr_employee_updation: data issue

### ISSUE THREAD

**Issue by abdallamohamedcore** [CybroOdoo/OpenHRMS#52]
Hello
There is issue that appear when i use this module "hr_employee_updation" because of data is commented in this file https://github.com/CybroOdoo/OpenHRMS/blob/13.0/hr_employee_updation/data/data.xml
as example in this method https://github.com/CybroOdoo/OpenHRMS/blob/13.0/hr_employee_updation/models/hr_employee.py#L104 call "employee_relationship"

**Comment by CybroOdoo** [comment]
Hi
We have fixed the issue, please get the updated version.

Thanks.
